config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books

  resources :meetings, only: [ :create, :update ]

  
  devise_for :users
  resources :users, only: [:show]

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :meetings, dependent: :destroy

	acts_as_taggable

  def available?
  	current_meeting.nil?
  end

  def current_meeting
  	meetings.on_date.first
  end

  def late?
  	!available? and (Time.now > (current_meeting.start_date + 2.days))
  end

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  scope :on_date, -> { where(end_date: nil) }
  scope :off, -> { where.not(end_date: nil) }

  def on_date?
  	end_date.nil?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, :phone_number, presence: true

	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  has_many :meetings, dependent: :destroy

  def current_book
    current_meeting.book
  end

  def current_meeting
    meetings.on_date.first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @meeting = current_user.meetings.build(book_id: @book.id)
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :user_id, :tag_list)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

before_action :set_meeting, only: :update

  def create
  	@meeting = Meeting.new(meeting_params)
  	@meeting.start_date = Time.now

  	@meeting.save
  	redirect_to root_path
  end

  def update
  	@meeting.update(meeting_params)
  	redirect_to root_path
  end


private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:book_id, :user_id, :start_date, :end_date)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :tag_list %>
    <%= f.hidden_field :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? && current_user.current_meeting %>
  <div class="alert alert-info" role="alert">
    당신은 <%= current_user.current_book.id %>번 책과 데이트 중입니다.
    <%= simple_form_for current_user.current_meeting do |f| %>
      <%= f.hidden_field :end_date, value: Time.now %>
      <%= f.submit "데이트 끝내기", class: "btn btn-default" %>
    <% end %>
  </div>
<% end %>

<h1>Listing Books</h1>

<table class = "table">
  <thead>
    <tr>
      <th>번호</th>
      <th>태그</th>
      <th>상태</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr class= "<%= "danger" if book.late? %>">
        <td><%= book.id %></td>
        <td><%= book.tag_list %></td>
        <td>
          <% if book.available? %>
            데이트 가능
          <% else %> 
            데이트 중
          <% end %>
        </td>
        <td><%= link_to 'Show', book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>번호: </strong>
  <%= @book.id %>
</p>

<p>
  <strong>태그: </strong>
  <%= @book.tag_list %>
</p>

<p>
  <strong>상태: </strong>
  	<% if @book.available? %>
      데이트 가능
    <% else %> 
		<% current_meeting = @book.current_meeting %>
      데이트 중 with <%= current_meeting.user.name %>
        <% if current_user.id == 1 %>
          (<%= current_meeting.user.phone_number %>)
        <% end %>
		<p>
  		<strong>데이트 시작일: </strong>
  		<%= current_meeting.start_date %>
		</p>
		<p>
  		<strong>데이트 마감일: </strong>
  		<%= current_meeting.start_date + 21.days %>
		</p>
    <% end %>
</p>

	<% if @book.available? && current_user.current_meeting.nil? %>
		<%= simple_form_for @meeting do |f| %>
			<%= f.hidden_field :user_id %>
			<%= f.hidden_field :book_id %>
			<%= f.submit "데이트 시작하기", class: "btn btn-default" %>
		<% end %>
	<% end %>

<br>

<% if current_user.id == 1 or current_user.id == @book.user_id %>
  <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-default" %> |
  <%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %> |
<% end %>

  <%= link_to 'Back', books_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bdb2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "BDB", root_path, class: "navbar-brand" %>
  	</div>
 	
		<ul class="nav navbar-nav navbar-right">
  		<% if user_signed_in? %>
        <li><%= link_to "My page", current_user, class: "navbar-right" %></li>
  			<li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-right" %></li>
  		<% else %>
  			<li><%= link_to "Log In", new_user_session_path, class: "navbar-right" %></li>
  		<% end %>
  	</ul>
  </div>
</nav>

<div class="container">
	<%= yield %>
</div>


</body>
</html>

app/views/meetings/create.html.erb
<h1>Meetings#create</h1>
<p>Find me in app/views/meetings/create.html.erb</p>

app/views/meetings/update.html.erb
<h1>Meetings#update</h1>
<p>Find me in app/views/meetings/update.html.erb</p>

app/views/users/show.html.erb
<h2> <%= current_user.name %> ( <%= current_user.phone_number %> ) </h2>

<h3> My books </h3>

<table class = "table" >
  <thead>
    <tr>
      <th>번호</th>
      <th>제목</th>
      <th>태그</th>
      <th>상태</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= link_to book.title, book %></td>
        <td><%= book.tag_list %></td>
        <td>
          <% if book.available? %>
            데이트 가능
          <% else %> 
            데이트 중
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Meeting Records </h3>

<table class = "table" >
  <thead>
    <tr>
      <th>번호</th>
      <th>태그</th>
      <th>시작일</th>
      <th>마감일</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.book.id %></td>
        <td><%= link_to meeting.book.tag_list %></td>
        <td><%= meeting.start_date %></td>
        <td><%= meeting.end_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>